
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "afak", targetNamespace = "http://hellosaiyed/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Afak {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserInfoByPin", targetNamespace = "http://hellosaiyed/", className = "client.GetUserInfoByPin")
    @ResponseWrapper(localName = "getUserInfoByPinResponse", targetNamespace = "http://hellosaiyed/", className = "client.GetUserInfoByPinResponse")
    @Action(input = "http://hellosaiyed/afak/getUserInfoByPinRequest", output = "http://hellosaiyed/afak/getUserInfoByPinResponse")
    public String getUserInfoByPin(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
